### ISSUE TITLE
Resolved?

### ISSUE THREAD

**Issue by dcorbin** [rajit/scala-mock-intellij#1]
Was this ever resolved for you?  If so, how? I'm having the same problem.

**Comment by rajit** [comment]
I used this repository to submit the issue to JetBrains, which can be seen here: https://youtrack.jetbrains.com/issue/SCL-6787

My memory says it begun working for me. If it has stopped working for you in the latest version of IntelliJ, feel free to use the repository to demonstrate the issue to JetBrains and post it to them.
